project:
  type: website

website:
  favicon: star-shine-svgrepo-com.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Education.qmd
      - Research.qmd
      - Experience.qmd
      - Leadership & Service.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

