project:
  type: website

website:
  title: "my_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Education.qmd
      - Research.qmd
      - Experience.qmd
      - Leadership & Service.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

