---
title: "Education"
---

### Duke University / Duke Kunshan University (Dual Degree)  
*Aug 2021 - Aug 2025*  

- **B.S. in Interdisciplinary Studies** (Data Science) awarded by Duke University, Durham, NC, USA  
- **B.S. in Data Science** awarded by DKU, Kunshan, China  

  **Relevant Courses**:  
  - Statistical Machine Learning, Computer Architecture, Advanced Data Visualization, Advanced Linear Algebra

### IES Abroad, Barcelona, Spain  
*Aug - Dec 2022*  

- **Relevant Courses**:  
  - Data Structures and Algorithms, Art and Design

## Honors

- Dean's List with Distinction: Fall 2021  
- Dean's List: Fall 2022  

## Skills

- **Programming**: Python, Java, C, R  
- **Tools**: Excel, Git, Gitlab, TensorFlow, PyTorch, QGIS/ArcGIS, React, MS Office  

## Languages

- English (Fluent), Arabic (Fluent), French (Fluent), Chinese Mandarin (Elementary), Spanish (Elementary)  

## Class Projects

### Survey on Incentive Mechanism Design in Federated Learning
Conducted as part of the CS402 (Artificial Intelligence) final project.  
**Link**: [Survey PDF](CS402_FP.pdf)

### Music Recommendation System Using Clustering Algorithms
Final project for Elements of Machine Learning at Duke Kunshan University.  
**Link**: [GitHub Repository](https://github.com/slaicha/MusicRecommendationSystem)

### Report on Aggregation Strategies in Federated Learning
A project report exploring aggregation algorithms, part of the Mathematics for Machine Learning course at Duke University.  
**Link**: [Report PDF](Math466_Final_Project.pdf)

### Advanced Data Visualization Project
Visualization project in STATS401 (Advanced Data Visualization), focusing on global water scarcity concerns.  
**Link**: [Visualization App](https://ameyasr24.shinyapps.io/project-2-app-ex/)
